name: Update Raw GitHub Links to ghp.ci Prefix

on:
  push:
    branches:
      - main  # 触发工作流的分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find and Update Links in Files
        run: |
          # 遍历所有 .txt 和 .json 文件，替换文件内容中的 https://raw.githubusercontent.com 前缀
          find . -type f \( -iname "*.txt" -o -iname "*.json" \) | while read -r file; do
            echo "Processing file: $file"
            # 使用 sed 替换文件中的链接前缀
            sed -i 's|https://raw.githubusercontent.com|https://ghp.ci/https://raw.githubusercontent.com|g' "$file"
          done

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update links in .txt and .json files to use https://ghp.ci" || echo "No changes to commit"
          git push
